### ISSUE TITLE
[Tracker] Repeating Fields Push to the Finish

### ISSUE THREAD

**Issue by rossriley** [bolt/bolt#4422]
1. How to see repeating fields in action? Add this to the bottom of your contenttypes.yml.

https://gist.github.com/rossriley/da5a932841286d5f23bb

### Still To Do.
-  [X] Javascript: As new groups are added and on load the name attribute of the html elements need to be indexed. The format should be `name="<repeatfieldname>[<index>][<elementname>]`
- [X] Javascript: Need to prevent adding more than the limit specified in `limit:`
- [x] PHP: Validate the YAML file to disallow certain configurations. Disallow unsupported field types.
- [x] PHP Controller: Posted values need normalising and passing to `->save()` method is same as used in tests here: https://github.com/bolt/bolt/blob/master/tests/phpunit/unit/Storage/FieldLoadTest.php#L88-L95
- [x] PHP / Frontend - Once this is working make sure that they are re-displayed on subsequent edits.
- [X] Set default values for fields so that editcontent works with ``strict_variables: true`` again
- [x] Select & multi-select currently populate first option as a default value

**Comment by rarila** [comment]
- [ ] Set default values for fields so that editcontent works with ``strict_variables: true`` again

**Comment by GawainLynch** [comment]
- [ ] Select & multi-select currently populate first option as a default value

**Comment by rarila** [comment]
How important from an UIX standpoint is duplicating? I see here some extra work todo

**Comment by Boorj** [comment]
@GawainLynch, i think your comment references also this issue: #4481 (*Set default option for type: select*)

**Comment by GawainLynch** [comment]
@Boorj no it is a different issue
