### ISSUE TITLE
[Tracker] Missing functionality for widgets.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#4444]
Our new widgets functionality works fine, but its missing a few specific pieces of functionality. I think we should get these done for 3 .0

  - [x] Add ``{% if haswidgets('..') %}`` functionality 
  - [x] Add `{{ listwidgets('..') }}` function, to get a list of currently registered widgets
  - [x] Make sure `priority` works. Or does it already? 
  - [x] Rename `widget` to `widgets`
  - [x] Make the widget insert script Vanilla Javascript instead of Jquery (see `app/theme_defaults/widgetjavascript.twig`)
  - [x] Make `{{ widgets() }}` use named parameters, and have 'frontend' be default. So, `{{ widgets('aside_top') }}` should work.
  - [x] Allow for a way to define the wrapper for the widget and widgetholder. This should be possible ~~both in code, as well as~~ in the theme.
  - [x] Add "Latest [x] from [x]" and "search" as widgets. 
  - [x] Write documentation
  - [ ] Add widget hooks on the user edit forms (Moved from #4966)

Do at some later point in time: 
  - [ ] Add permission check for widgets, perhaps?
  - [ ] Allow for a max number of widgets in a given widget area

**Comment by GawainLynch** [comment]
> Add permission check for widgets, perhaps?

Can I vote against that as it is starting to produce extra complexity that really doesn't belong here.

> Allow for a max number of widgets in a given widget area

Valid, absolutely… Question on my mind though, are we inviting race type conditions with people setting bigger and bigger priorities to out do each other… `**cough**` WordPress `**cough**`

**Comment by bobdenotter** [comment]
> Can I vote against that as it is starting to produce extra complexity that really doesn't belong here.

Ok, let's scrap that for now, at least. 

> Valid, absolutely… Question on my mind though, are we inviting race type conditions…

Let's put that one on the backburner too. We can always introduce it, if it becomes an issue.

**Comment by bobdenotter** [comment]
Documentation is in PR. 

Other changes will be bumped to 3.1.

**Comment by bobdenotter** [comment]
Closing!
