### ISSUE TITLE
[Tracker] Documentation updates

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#4503]
This issue is intended to track the outstanding work on documenting changes in 3.0 that are potential blockers for release.

- [ ] Asset management (JavaScript, CSS & Widgets) @GawainLynch & @bobdenotter
- [ ] Asset queues @GawainLynch
- [ ] Controllers @GawainLynch & @CarsonF
- [x] Deprecations — [c.f. wiki](https://github.com/bolt/bolt/wiki/Deprecations-Tracker)
- [ ] Extension initialize() and before() middleware @GawainLynch & @CarsonF
- [ ] Routing @GawainLynch & @CarsonF
- [ ] Schema extending @GawainLynch
- [ ] Schema management @GawainLynch
- [ ] Services @rossriley, @GawainLynch & @CarsonF
- [ ] Session internals @CarsonF
- [ ] Storage internals @rossriley
- [ ] Getting Repeaters to iterate over in templates.
- [x] Widgets @bobdenotter
