### ISSUE TITLE
[Tracker] Symfony 3 Blockers for Bolt v4

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#4583]
This is to track the upstream packages that have dependencies on Symfony components, but don't optionally allow Symfony 3.

- [x] `ua-parser/uap-php` **[PR https://github.com/ua-parser/uap-php/pull/26]**
- [x] `stecman/symfony-console-completion` **[PR https://github.com/stecman/symfony-console-completion/pull/64]**
- [x] `codeception/codecepion` **[PR https://github.com/Codeception/Codeception/pull/2642]**

Deprecation notices: #4508

**Comment by GawainLynch** [comment]
All upstream packages now have optional Symfony 3 support.
