### ISSUE TITLE
[Tracker] Tracker issue list for Repeater Fields.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#5435]
There are a few bugs and quirks with Repeater Fields. Most of them fall in two categories: 
- Issues when repeaters are used in template-fields, or 'exotic' fields like template-select is used in Repeaters.
- Issues with naming: Quirks appear when using field/taxonomy/contenttype names with `_` or `-` (underscores and hyphens).

This issue bundles them, so we can keep track of their status, and to make it easier to see which ones are duplicates. 
- [x] custom fields not working in repeater field, bug? #5403
- [ ] [BUG] Duplicate Set does not duplicate HTML field contents unless record is saved first. #5476

Features: 
- [x] [RFC] Repeater fields: Allow for multiple subtypes / blocks #5307

Done: 
- [x] [BUG] Repeaters in templatefields is throwing an error #5183
- [x] [BUG] Repeater fields as 'templatefields' in theme.yml #5320
- [x] BUG Not able to use - (hyphen) in field name for repeating fields #5348
- [x] [BUG] repeater field // HTML editor // does not store #5428
- [x] [BUG] repeater field // HTML editor // shows up twice #5427
- [x] Bug // content of repeater fields lost #5426
- [x] [Bug] Duplicate Set button not working #5406

See also: [Search for 'repeater' in open issues](https://github.com/bolt/bolt/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+repeater)

**Comment by chrispmiller** [comment]
I have similar problem with the html field not saving on update (bolt 3.0.4 ). I made the fix above (#5428), but the problem remains. I noticed if i change the the content type from html to textarea the updates are stored. Also when the content type is html then the last item in the repeater list does update.

**Comment by bajesus** [comment]
I'm seeing the exact same issue as chrispmiller.  I updated to 3.0.7 and the issue is still going on.  The last html field and all of the non-html fields are sending fine, but any previous html fields aren't updating when posted.  I think it is an issue with the id attribute for those textareas and how CKeditor is being initiated on them.  The id attribute is set to the same thing on all of them (I called my html field "content" and all of the hidden textareas are set to id="content").

**Comment by saltpeanuts** [comment]
Same here regarding #5428 In 3.0.7, I'm still seeing issue #5427 too.

**Comment by flrvt** [comment]
On top of the issues @saltpeanuts mentioned, I am seeing a new issue on my 3.0.7 install regarding markdown fields, documented in #5489

**Comment by SahAssar** [comment]
Crossed out "Repeater fields: Allow for multiple subtypes" because that PR has been merged, so only the HTML duplicate issue left on this. Haven't checked that bug on 3.3 yet, so that might be done too, I'll check it soon.
