### ISSUE TITLE
[Tracker] Bolt 4.0 Clean-up List

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#6403]
## NOTE TO NON-CORE TEAM MEMBERS

This tracker issue is **not** the place for bugs, feature requests, drop bear sightings, or general conversation. Please either open an new issue for bug/feature requests, or head over to Slack or the forum for support

---

Some of the work in this list will obviously land in various 3.x branches over time in preparation, but the intent is to keep, and **update** (HINT! HINT!) the list of stuff to replace/update/rip-out in 4.0-dev.

- [ ] Symfony
  - [x] Implement Symfony v3.2+
  - [ ] Remove _known_ SF 4 deprecations 
- [x] Silex 2
  - [x] Service providers
  - [x]  `$app->share()` removal
  - [x]  `$app->factory()` implementation
  - [x] Remove all use of `$app['request']` (2017-02-26 should be gone from non-deprecated classes, but still need said classes removed)
- [x] Symfony Security
  - [x] Replace PasswordHashManager
  - [x] Enforce backend routes
  - [x] Replace `Bolt\Users`
- [ ] Twig
  - [x] Remove v1 deprecations (heavily dependent on the DTO work first)
  - [x] Update to v2
  - [ ] Remove use of runtime globals
  - [x] Remove non-namespace path use
- [ ] Monolog
  - [ ] Implement v2
  - [ ] Rework logging services
- [ ] Storage
  - [ ] Remove `Bolt\Legacy\Storage`
  - [ ] Ensure Doctrine ORM can be a "drop-in"
- [x] Remove `Bolt\Configuration\ResourceManager`
- [ ] `Bolt\Config`
  - [ ] Remove legacy class
  - [ ]  Remove transitory validators
- [ ] Remove `Bolt\Legacy\Content`
- [x] Remove `Bolt\Library`
- [ ] Nut console
  - [ ] Remove default injection of application object
  - [x] Implement a container aware interface for commands that require app
- [x]  Caching
  - [x] PSR-6 caches
  - [x] PSR-16 simple caches
- [ ]  Controllers
  - [ ] Route parameter clean up
- [ ]  CamelCase all the thingz

**Comment by SahAssar** [comment]
@GawainLynch Quick question on this: is this still Up To Date (with regards to silex/flex)? It mentions "Silex 2" so I'll assume not. Do you want to update it or should we close and open a new later?

**Comment by GawainLynch** [comment]
Yeah, I'll update in the new year. It is going to take some time before then to get a clear picture of what needs doing.

**Comment by JarJak** [comment]
Closing since most of them are done or not actual.
