### ISSUE TITLE
[Tracker] Wireframes Bolt 3.x backend

### ISSUE THREAD

**Issue by sbonardt** [bolt/bolt#7595]
To get to a solid design process, we'll need to document and create wireframes of the current Bolt backend. These wireframes will subsequently be the basis for the new 4.0 wireframes: We can modify, enhance and build upon all the work already done.

This issue is to document this first step of getting to a base wireframes set. As we are making the wireframes based on the current status, there's not much room for discussion: things currently are as they are off course. But feel free to speak out if you feel there is anything missing!

**Comment by sbonardt** [comment]
Looking at the current Bolt backend, the next set of wireframes are planned:

**Content editing:**
- [x] Dashboard
- [x] Dashboard - overview of navigation items, overlays, popups etc
- [x] Content type listing/overview page
- [x] Edit content page (general base fields)

**Configuration:**
- [x] Users & permissions
- [x] Roles 
- [ ] (Database check/update) - edit, might skip

**Other:**
- [x] File management
- [x] Separate wireframe with all fields available in Bolt core

**Comment by sbonardt** [comment]
# Content editing Wireframes Bolt 3.x #
Here are the first versions for the "Content editing" part of the backend wireframes. I've created small screen/mobile and large screen/desktop wireframes. 

Note these wireframes are high in detail! Sometimes I've used specific texts from the backend in stead of 'Lorem ipsum', as those parts are important functionally for the UI/user experience. 

The wireframes are created with Sketch. For the new Bolt 4 Wireframes we might use an online wireframe tool. Any suggestions welcome.

*PS: click on the separate img's to view them on black in a separate tab*
<br><br>

## Dashboard - 01 small screens ##
<p align="center">
<img src="https://user-images.githubusercontent.com/5597447/43964394-11c49e88-9cbd-11e8-9681-ecbdcaf70c99.jpg">
</p>
<br><br>

## Dashboard - 02 large screens ##

<p align="center">
<img src="https://user-images.githubusercontent.com/5597447/43964395-11dd30f6-9cbd-11e8-8669-4df081f5b596.jpg">
</p>
<br><br>

## Navigation Overlays - 01 small screens - popups ##

<p align="center">
<img src="https://user-images.githubusercontent.com/5597447/43964401-12626744-9cbd-11e8-935d-1fe0b55ff8b8.jpg">
</p>
<br><br>

## Navigation Overlays - 02 main navigation - small screens ##

<p align="center">
<img src="https://user-images.githubusercontent.com/5597447/43964402-127bf1c8-9cbd-11e8-9b56-e6acf114f7a2.jpg">
</p>
<br><br>

## Navigation Overlays - 03 main navigation - large screens ##

<p align="center">
<img src="https://user-images.githubusercontent.com/5597447/43964403-129a82c8-9cbd-11e8-8e17-1530babe6675.jpg">
</p>
<br><br>

## Content type overview - 01 small screens ##
<p align="center">
<img src="https://user-images.githubusercontent.com/5597447/43964391-11910870-9cbd-11e8-8927-4745cf58e2f9.jpg">
</p>
<br><br>

## Content type overview - 02 large screens ##
<p align="center">
<img src="https://user-images.githubusercontent.com/5597447/43964393-11acb930-9cbd-11e8-86cf-9102235d29ee.jpg">
</p>
<br><br>

## Edit Content - 01 no tabs - small screens ##
<p align="center">
<img src="https://user-images.githubusercontent.com/5597447/43964396-11f7143a-9cbd-11e8-87f7-b27a55a3d403.jpg">
</p>
<br><br>

## Edit Content - 02 no tabs - large screens ##
<p align="center">
<img src="https://user-images.githubusercontent.com/5597447/43964398-120f2ab6-9cbd-11e8-8c10-dfc1e3735671.jpg">
</p>
<br><br>

## Edit content - 03 tabbed - small screens ##
<p align="center">
<img src="https://user-images.githubusercontent.com/5597447/43964399-122cb784-9cbd-11e8-9094-4e2caefab045.jpg">
</p>
<br><br>

## Edit content - 04 tabbed - large screens ##
<p align="center">
<img src="https://user-images.githubusercontent.com/5597447/43964400-12487668-9cbd-11e8-8709-5fb9e3b320e7.jpg">
</p>
<br><br>

**Comment by sbonardt** [comment]
<h2>Users - 01</h2>
<img src="https://user-images.githubusercontent.com/5597447/44097013-0c87ba68-9fdd-11e8-8728-980437fda55f.jpg">
<br><br>

<h2>Roles - 01</h2>
<img src="https://user-images.githubusercontent.com/5597447/44097012-0c6febcc-9fdd-11e8-985b-cb5eed2db2d9.jpg">
<br><br>

<h2>File management - 01 small screens</h2>
<img src="https://user-images.githubusercontent.com/5597447/44097054-23133d52-9fdd-11e8-8a2e-e0a4db1a7de4.jpg">
<br><br>

<h2>File management - 02 large screens</h2>
<img src="https://user-images.githubusercontent.com/5597447/44097053-22fc4c6e-9fdd-11e8-9640-e357f496ad09.jpg">
<br><br>

<h2>All content type fields - 01 small screens</h2>
<img src="https://user-images.githubusercontent.com/5597447/44097051-22e166ba-9fdd-11e8-8fbe-9f55a7ee463e.jpg">
<br><br>

<h2>All content type fields - 02 large screens</h2>
<img src="https://user-images.githubusercontent.com/5597447/44097050-22c86d22-9fdd-11e8-9a74-69e4ecd574fd.jpg">
<br><br>

**Comment by sbonardt** [comment]
OK. So all defined screens are in for Bolt 3.x I suggest we use this as a basis for creating the set for 4.x

I'll create separate issues per screen, so we can focus on the functionality, changes and additions on each screen separately. It'll be a lot of extra issues, but that will also allow us some proper tracking, commenting, and feedback.
